services:
  catalog-service:
    image: ghcr.io/shythm/catalog-service
    container_name: catalog-service
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  config-service:
    image: ghcr.io/shythm/config-service
    container_name: config-service
    ports:
      - 8888:8888
